"""Болотный Хаб «Добро пожаловать»: cut public/hub/ep0/voice.mp3 from the takes and write src/hub/ep0.ts.

Each row: take, cut [from, to] in take seconds, captions (text, take seconds), shot (img, size, cam a, cam b).
usage: python3 tools/hub_ep0.py && npx prettier --write src/hub/ep0.ts
"""
import json
import subprocess

D = "public/hub/ep0/"
L, N, PAY, CAP, PLUS, DED = [D + x for x in ("take-long.mp3", "take-names.mp3", "take-pay.mp3", "take-capsules.mp3", "take-plus.mp3", "take-dedkod.mp3")]
V, S = [941, 1672], [1536, 1024]
ROWS = [
    (L, 0.0, 4.1, [("Добро пожаловать", 0), ("в «Трындец корпорейшн»", 1.8)], ("scenes/ep0-lobby", V, (470, 836, 1672), (600, 650, 1150))),
    (N, 4.5, 6.32, [("Снежана Вайбовна", 4.7)], ("scenes/ep6-water", V, (520, 760, 1350), (540, 600, 1000))),
    (N, 2.35, 3.95, [("Глеб Стартапович", 2.4)], ("scenes/ep5-socks", V, (470, 700, 1250), (470, 600, 1000))),
    (PAY, 0.0, 1.95, [("Оплата тикетами", 0)], ("scenes/ep0-cashier", V, (470, 836, 1672), (620, 900, 1100))),
    (N, 0.0, 1.55, [("Мидл Тимоша", 0)], ("chars/timosha", S, (1080, 560, 1000), (1070, 500, 820))),
    (L, 23.0, 27.2, [("Разрешаем пилить", 23.12), ("B2B SaaS по выходным", 25.02)], ("scenes/ep0-weekend", V, (470, 836, 1672), (520, 950, 1250))),
    (N, 6.99, 8.95, [("Помидор Эджайлович", 7.04)], ("chars/pomidorych", S, (1100, 560, 1024), (1100, 480, 760))),
    (CAP, 0.0, 5.35, [("В офисе есть капсулы сна", 0), ("Домой ездить необязательно", 2.6)], ("scenes/ep0-capsule", V, (470, 836, 1672), (380, 900, 1150))),
    (N, 9.36, 11.07, [("Жорж Скрамник", 9.42)], ("chars/zhorzh", V, (470, 600, 1100), (470, 836, 1672))),
    (DED, 0.0, 1.55, [("Дедкод Легаси", 0)], ("chars/dedkod", S, (1130, 560, 1024), (1130, 460, 760))),
    (PLUS, 0.0, 7.25, [("Каждому сотруднику положен", 0), ("«Трындец Плюс» —", 2.42), ("дополнительные задачи", 4.22), ("без доплаты", 6.0)], ("scenes/ep0-gift", V, (470, 836, 1672), (560, 1000, 1150))),
]
GAP = 0.45

inputs, filt, shots, caps, t = [], [], [], [], 0.0
for i, (take, a, b, cs, shot) in enumerate(ROWS):
    inputs += ["-i", take]
    d = b - a
    filt.append(
        f"[{i}:a]aresample=44100,aformat=channel_layouts=mono,atrim={a}:{b},asetpts=PTS-STARTPTS,"
        f"afade=t=in:d=0.03,afade=t=out:st={d - 0.06:.3f}:d=0.06,apad=pad_dur={GAP}[p{i}]"
    )
    shots.append((max(0.0, t - 0.15) if i else 0.0, shot))
    caps += [(txt, round(st + t - a, 2)) for txt, st in cs]
    t += d + GAP
filt.append("".join(f"[p{i}]" for i in range(len(ROWS))) + f"concat=n={len(ROWS)}:v=0:a=1[out]")
subprocess.run(["ffmpeg", "-v", "error", "-y", *inputs, "-filter_complex", ";".join(filt), "-map", "[out]", "-b:a", "192k", D + "voice.mp3"], check=True)

cam = lambda c: "{ cx: %d, cy: %d, h: %d }" % c
shot_lines = "\n".join(f'  {{ img: "{img}", size: [{sz[0]}, {sz[1]}], from: {fr:.2f}, a: {cam(a)}, b: {cam(b)} }},' for fr, (img, sz, a, b) in shots)
cap_lines = "\n".join(f"    {{ text: {json.dumps(x, ensure_ascii=False)}, at: {at} }}," for x, at in caps)
open("src/hub/ep0.ts", "w").write(f'''import type {{ HubEpisode, HubShot }} from "./Episode";

// «Добро пожаловать». Generated by tools/hub_ep0.py from the takes in public/hub/ep0: name / perk, interleaved.
const shots: HubShot[] = [
{shot_lines}
];

export const welcome: HubEpisode = {{
  id: "Welcome",
  voice: "hub/ep0/voice.mp3",
  end: {round(t + 1.2, 2)},
  musicFrom: 72,
  shots,
  captions: [
{cap_lines}
  ],
}};
''')
